{
    "port": 9001,

    "server_name": "potato annotator",

    "annotation_task_name": "Word Intrusion V2",

    # "annotation_task_name": "Match findings (Biology)",

    # Potato will write the annotation file for all annotations to this
    # directory, as well as per-annotator output files and state information
    # necessary to restart annotation.
    "output_annotation_dir": "annotation_output/output_word_intrusion_acl/",

    # The output format for the all-annotator data. Allowed formats are:
    # * jsonl
    # * json (same output as jsonl)
    # * csv
    # * tsv
    #
    "output_annotation_format": "jsonl",

    # If annotators are using a codebook, this will be linked at the top to the
    # instance for easy access
    "annotation_codebook_url": "",

    "data_files": [
        "data_files/ACL_OCL_topics.json"
    ],
    
    "item_properties": {
        "id_key": "id",
        "text_key": "id",
        "context_key": "context",
    },

    "user_config": {

      "allow_all_users": True,

      "users": [  ],
    },
    
    "alert_time_each_instance": 900,
    # defining the ways annotators entering the annotation system
    "login": {
       "type": 'password',    #can be 'password' or 'url_direct'
       "url_argument": 'PROLIFIC_PID' # when the login type is set to 'url_direct', 'url_argument' must be setup for a direct url argument login
    },
    #the jumping-to-id function will be disabled if "jumping_to_id_disabled" is True
    "jumping_to_id_disabled": True,

    #the navigation bar will be hidden to the annotators if "hide_navbar" is True
    "hide_navbar": True,

    # define the surveyflow of the system, set up the pages before and after the data annotation page
    "surveyflow": {
      "on": True,
      #"order" : ['pre_annotation', 'prestudy_passed', 'prestudy_failed', 'post_annotation'],
      "order" : ['pre_annotation', 'post_annotation'],
      "pre_annotation": ['surveyflow/intro.jsonl', 'surveyflow/instruction.jsonl', 'surveyflow/consent.jsonl'],
      "prestudy_passed": ['surveyflow/prestudy_pass.jsonl'],
      "prestudy_failed": ['surveyflow/prestudy_fail.jsonl'],
     # "post_annotation": ['surveyflow/experience.jsonl', 'surveyflow/end.jsonl'],
       "post_annotation": ['surveyflow/end.jsonl'],
      # If set, we will automatically generate testing questions similar to the annotation instances, but explicitly ask the annotator to choose one option
      "testing": [],
    },
    
    #prestudy test, annotators who fail this test will be disallowed to continue annotation
    "prestudy": {
        "on": False,
        "minimum_score": 0.8,
        "groundtruth_key": 'whether_match',
        "question_key": 'Whether the presented sentences are discussing the same scientific finding',
        "answer_mapping": {'Yes': True, 'No': False},
        "pass_page": 'surveyflow/prestudy_pass.jsonl',
        "fail_page": 'surveyflow/prestudy_fail.jsonl'
    },


    "automatic_assignment": {
      #whether do automatic task assignment for annotators, default False.
      "on": True,
      "output_filename": 'task_assignment.json',
      "sampling_strategy": 'random',
      "labels_per_instance": 10,
      "instance_per_annotator": 10,
      "test_question_per_annotator": 0, # you must set up the test question in surveyflow to use this function

      "users": [  ],
    },


    # How many seconds do you want the annotators spend on each instance, after
    # that, an alert will be sent per alert_time_each_instance seconds.
    "alert_time_each_instance": 10000000,
    "horizontal_key_bindings": true,

    "annotation_schemes": [      
        {
            "annotation_type": "radio",
            "name": "Word_Intrusion",
            "description": "Which of the following words is <em>intruder</em>: out of place or not related to the other words semantically?",
            "dynamic_labels": True, #set this true if you need dynamic labels for each instance
            "labels": [
               {"name": "{{instance_obj.labels[0]}}"},
               {"name": "{{instance_obj.labels[1]}}"},
               {"name": "{{instance_obj.labels[2]}}"},
               {"name": "{{instance_obj.labels[3]}}"},
               {"name": "{{instance_obj.labels[4]}}"},
               {"name": "{{instance_obj.labels[5]}}"},
            ], #please make sure "labels" are in the input data

            # If true, numbers [1-len(labels)] will be bound to each
            # label. Check box annotations with more than 10 are not supported
            # with this simple keybinding and will need to use the full item
            # specification to bind all labels to keys.
            "sequential_key_binding": True,
            "label_requirement": { "required": True },
        },       
      {
        "annotation_type": "slider",
        "name": "efforts",
        "description": "It was easy to identify the intruder word",
        "min_label": "Strongly disagree",
        "max_label": "Strongly agree",
        "label_requirement": { "required": True },
        "size": 5,
        "min_value": -1,
        "max_value": 100,
        "starting_value": -1,
        "sequential_key_binding": True,
      },        
        {
            "annotation_type": "text",
            "name": "Topic_Rationale",
            "label_requirement": { "required": True },
            "description": "Please provide a detailed rationale behind your input",
            "textarea": {
                  "on": True,
                  "rows": 5,
                  "cols": 100
            }
        }
    ],

    # The html that changes the visualiztation for your task. Change this file
    # to influence the layout and description of your task. This is not a full
    # HTML page, just the piece that does lays out your task's pieces
    #"html_layout": "templates/examples/fixed_keybinding_layout.html",
    "html_layout": "default",

    # The core UI files for Potato. You should not need to change these normally.
    #
    # Exceptions to this might include:
    # 1) You want to add custom CSS/fonts to style your task
    # 2) Your layout requires additional JS/assets to render
    # 3) You want to support additional keybinding magic
    #
    # if you want to use your own template,
    # please replace the string as a path to the template
    "base_html_template": "default",
    "header_file": "default",

    # This is where the actual HTML files will be generated
    "site_dir": "default"
}